github:
  token: <your github token>

keys:
  switch_tab_right: shift+right
  switch_tab_left: shift+left
  quit: ctrl+c
  refresh: ctrl+r
  live_mode: ctrl+l
  enter: enter
  tab: tab

settings:
  live_mode:
    enabled: true # to enable live mode at startup
    interval: 15s  # interval to refresh the page
